// Icon — 디자인의 Material Symbols 이름을 lucide-react-native 아이콘으로 매핑
import { Text, View } from 'react-native'
import {
  Plus,
  CableCar,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Sparkles,
  Waves,
  Ban,
  Bookmark,
  BookmarkPlus,
  CalendarDays,
  Phone,
  PartyPopper,
  CircleCheck,
  ChevronRight,
  Circle,
  X,
  ArrowLeftRight,
  Ticket,
  Copy,
  Ship,
  Footprints,
  GripVertical,
  TriangleAlert,
  ChevronDown,
  ChevronUp,
  Compass,
  Utensils,
  Coffee,
  Flame,
  Hospital,
  Shield,
  Car,
  House,
  Hotel,
  Keyboard,
  Languages,
  Layers,
  Lightbulb,
  Store,
  Stethoscope,
  MapPin,
  Map as MapIcon,
  Crosshair,
  Navigation,
  Navigation2,
  Moon,
  Bell,
  TreePine,
  CreditCard,
  User,
  Camera,
  Images,
  ScreenShare,
  QrCode,
  Minus,
  UtensilsCrossed,
  Soup,
  Route,
  Bookmark as Save,
  CalendarClock,
  Search,
  Share2,
  Fish,
  ShoppingBag,
  Milestone,
  Bot,
  MessageSquare,
  Siren,
  Sparkle,
  Star,
  TrainFront,
  Thermometer,
  Compass as Tour,
  SlidersHorizontal,
  ShieldCheck,
  Volume2,
  VolumeX,
  Headphones,
  Megaphone,
  WifiOff,
  Crown,
  Mic,
  Apple,
  LayoutGrid,
  Sun,
  Wind,
  MoveUpRight,
  History,
  Users,
  Building2,
  Info,
  ExternalLink,
  Cloud,
  CloudSun,
  CloudRain,
  CloudSnow,
  CloudFog,
  CloudLightning,
  Droplets,
  type LucideIcon,
  RotateCw,
  Wallet,
} from 'lucide-react-native'

const MAP: Record<string, LucideIcon> = {
  add: Plus,
  info: Info,
  open_in_new: ExternalLink,
  place: MapPin,
  aerial_way: CableCar,
  cable: CableCar,
  apple: Apple,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_right_alt: ArrowRight,
  arrow_upward: ArrowUp,
  north_east: MoveUpRight,
  auto_awesome: Sparkles,
  beach_access: Waves,
  waves: Waves,
  block: Ban,
  bookmark: Bookmark,
  bookmark_add: BookmarkPlus,
  brightness_high: Sun,
  calendar_today: CalendarDays,
  call: Phone,
  phone: Phone,
  celebration: PartyPopper,
  festival: PartyPopper,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  circle: Circle,
  close: X,
  compare_arrows: ArrowLeftRight,
  swap_horiz: ArrowLeftRight,
  confirmation_number: Ticket,
  wallet: Wallet,
  refresh: RotateCw,
  local_activity: Ticket,
  content_copy: Copy,
  directions_boat: Ship,
  directions_walk: Footprints,
  drag_indicator: GripVertical,
  emergency: TriangleAlert,
  warning: TriangleAlert,
  expand_more: ChevronDown,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  explore: Compass,
  food: Utensils,
  restaurant: Utensils,
  restaurant_menu: UtensilsCrossed,
  cafe: Coffee,
  local_cafe: Coffee,
  local_fire_department: Flame,
  local_hospital: Hospital,
  medical_services: Stethoscope,
  local_police: Shield,
  local_taxi: Car,
  home: House,
  hotel: Hotel,
  keyboard: Keyboard,
  language: Languages,
  translate: Languages,
  layers: Layers,
  lightbulb: Lightbulb,
  market: Store,
  storefront: Store,
  location_on: MapPin,
  near_me: Navigation,
  navigation: Navigation,
  // 정북 화살표 — 방위(나침반) 표시용. lucide navigation은 북동 45° 글리프라 방위에 쓰면 틀어진다.
  navigation_2: Navigation2,
  map: MapIcon,
  my_location: Crosshair,
  nightlife: Moon,
  notifications: Bell,
  park: TreePine,
  holiday_village: House,
  payments: CreditCard,
  person: User,
  photo_camera: Camera,
  photo_library: Images,
  present_to_all: ScreenShare,
  qr_code_scanner: QrCode,
  qr_code: QrCode,
  remove: Minus,
  ramen_dining: Soup,
  set_meal: Fish,
  route: Route,
  signpost: Milestone,
  save: Save,
  schedule: CalendarClock,
  search: Search,
  settings: SlidersHorizontal,
  tune: SlidersHorizontal,
  share: Share2,
  shopping_bag: ShoppingBag,
  smart_toy: Bot,
  sms: MessageSquare,
  support_agent: MessageSquare,
  sos: Siren,
  spa: Sparkle,
  star: Star,
  subway: TrainFront,
  groups: Users,
  thermostat: Thermometer,
  tour: Tour,
  verified_user: ShieldCheck,
  volume_up: Volume2,
  volume_off: VolumeX,
  headphones: Headphones,
  megaphone: Megaphone,
  wifi_off: WifiOff,
  sim_card: CreditCard,
  workspace_premium: Crown,
  mic: Mic,
  receipt_long: CreditCard,
  history: History,
  layers_alt: Layers,
  wind: Wind,
  thermostat_auto: Thermometer,
  buildings: Building2,
  // 날씨 컨디션 (Open-Meteo WMO 코드 매핑용)
  weather_clear: Sun,
  weather_partly: CloudSun,
  weather_cloudy: Cloud,
  weather_rain: CloudRain,
  weather_snow: CloudSnow,
  weather_fog: CloudFog,
  weather_storm: CloudLightning,
  humidity: Droplets,
}

export type IconProps = {
  name: string
  size?: number
  color?: string
  filled?: boolean
  strokeWidth?: number
}

// 통역(번역) 글리프 — 한글/영어를 나타내는 "한A" 텍스트 아이콘. 모든 화면 통역 아이콘 통일.
function TranslateGlyph({ size, color }: { size: number; color: string }) {
  return (
    <View
      style={{
        width: size,
        height: size,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Text
        style={{
          fontSize: size * 0.62,
          fontWeight: '900',
          color,
          includeFontPadding: false,
        }}>
        한
      </Text>
      <Text
        style={{
          fontSize: size * 0.52,
          fontWeight: '900',
          color,
          includeFontPadding: false,
          marginLeft: size * 0.04,
        }}>
        A
      </Text>
    </View>
  )
}

export function Icon({
  name,
  size = 20,
  color = '#18181B',
  filled = false,
  strokeWidth,
}: IconProps) {
  // 통역 아이콘은 한/영(한A) 글리프로 통일
  if (name === 'translate') return <TranslateGlyph size={size} color={color} />
  const Cmp = MAP[name] ?? Circle
  // lucide는 아웃라인 아이콘 — 복잡한 아이콘(식기·자동차·청진기 등)을 솔리드로 채우면
  // 내부 디테일이 사라져 작은 크기에서 "색 덩어리"로 뭉개진다. 그래서 filled는 기본
  // 아웃라인으로 또렷하게 렌더하고, 솔리드가 의미 있는 점·배지·별 류만 실제로 채운다.
  const solidFill = filled && SOLID_FILL.has(name)
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={strokeWidth ?? 2}
      fill={solidFill ? color : 'transparent'}
    />
  )
}

// filled 시 실제 솔리드로 채울 아이콘(단순 형태 — 점·배지·별·북마크 등). 그 외는 아웃라인.
const SOLID_FILL = new Set([
  'circle',
  'check_circle',
  'star',
  'bookmark',
  'bookmark_add',
  'local_activity',
  'verified',
  'workspace_premium',
])
