// Icon — 디자인의 Material Symbols 이름을 lucide-react-native 아이콘으로 매핑
import {
  Plus,
  CableCar,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Sparkles,
  Waves,
  Ban,
  Bookmark,
  BookmarkPlus,
  CalendarDays,
  Phone,
  PartyPopper,
  CircleCheck,
  ChevronRight,
  Circle,
  X,
  ArrowLeftRight,
  Ticket,
  Copy,
  Ship,
  Footprints,
  GripVertical,
  TriangleAlert,
  ChevronDown,
  ChevronUp,
  Compass,
  Utensils,
  Coffee,
  Flame,
  Hospital,
  Shield,
  Car,
  House,
  Hotel,
  Keyboard,
  Languages,
  Layers,
  Lightbulb,
  Store,
  Stethoscope,
  MapPin,
  Map as MapIcon,
  Crosshair,
  Navigation,
  Moon,
  Bell,
  TreePine,
  CreditCard,
  User,
  Camera,
  Images,
  ScreenShare,
  QrCode,
  Minus,
  UtensilsCrossed,
  Soup,
  Route,
  Bookmark as Save,
  CalendarClock,
  Search,
  Share2,
  Fish,
  ShoppingBag,
  Milestone,
  Bot,
  MessageSquare,
  Siren,
  Sparkle,
  Star,
  TrainFront,
  Thermometer,
  Compass as Tour,
  SlidersHorizontal,
  ShieldCheck,
  Volume2,
  VolumeX,
  WifiOff,
  Crown,
  Mic,
  Apple,
  LayoutGrid,
  Sun,
  Wind,
  MoveUpRight,
  History,
  Users,
  Building2,
  Info,
  ExternalLink,
  type LucideIcon,
} from 'lucide-react-native'

const MAP: Record<string, LucideIcon> = {
  add: Plus,
  info: Info,
  open_in_new: ExternalLink,
  place: MapPin,
  aerial_way: CableCar,
  cable: CableCar,
  apple: Apple,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_right_alt: ArrowRight,
  arrow_upward: ArrowUp,
  north_east: MoveUpRight,
  auto_awesome: Sparkles,
  beach_access: Waves,
  waves: Waves,
  block: Ban,
  bookmark: Bookmark,
  bookmark_add: BookmarkPlus,
  brightness_high: Sun,
  calendar_today: CalendarDays,
  call: Phone,
  phone: Phone,
  celebration: PartyPopper,
  festival: PartyPopper,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  circle: Circle,
  close: X,
  compare_arrows: ArrowLeftRight,
  swap_horiz: ArrowLeftRight,
  confirmation_number: Ticket,
  local_activity: Ticket,
  content_copy: Copy,
  directions_boat: Ship,
  directions_walk: Footprints,
  drag_indicator: GripVertical,
  emergency: TriangleAlert,
  warning: TriangleAlert,
  expand_more: ChevronDown,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  explore: Compass,
  food: Utensils,
  restaurant: Utensils,
  restaurant_menu: UtensilsCrossed,
  cafe: Coffee,
  local_cafe: Coffee,
  local_fire_department: Flame,
  local_hospital: Hospital,
  medical_services: Stethoscope,
  local_police: Shield,
  local_taxi: Car,
  home: House,
  hotel: Hotel,
  keyboard: Keyboard,
  language: Languages,
  translate: Languages,
  layers: Layers,
  lightbulb: Lightbulb,
  market: Store,
  storefront: Store,
  location_on: MapPin,
  near_me: Navigation,
  navigation: Navigation,
  map: MapIcon,
  my_location: Crosshair,
  nightlife: Moon,
  notifications: Bell,
  park: TreePine,
  holiday_village: House,
  payments: CreditCard,
  person: User,
  photo_camera: Camera,
  photo_library: Images,
  present_to_all: ScreenShare,
  qr_code_scanner: QrCode,
  qr_code: QrCode,
  remove: Minus,
  ramen_dining: Soup,
  set_meal: Fish,
  route: Route,
  signpost: Milestone,
  save: Save,
  schedule: CalendarClock,
  search: Search,
  settings: SlidersHorizontal,
  tune: SlidersHorizontal,
  share: Share2,
  shopping_bag: ShoppingBag,
  smart_toy: Bot,
  sms: MessageSquare,
  support_agent: MessageSquare,
  sos: Siren,
  spa: Sparkle,
  star: Star,
  subway: TrainFront,
  groups: Users,
  thermostat: Thermometer,
  tour: Tour,
  verified_user: ShieldCheck,
  volume_up: Volume2,
  volume_off: VolumeX,
  wifi_off: WifiOff,
  sim_card: CreditCard,
  workspace_premium: Crown,
  mic: Mic,
  receipt_long: CreditCard,
  history: History,
  layers_alt: Layers,
  wind: Wind,
  thermostat_auto: Thermometer,
  buildings: Building2,
}

export type IconProps = {
  name: string
  size?: number
  color?: string
  filled?: boolean
  strokeWidth?: number
}

export function Icon({
  name,
  size = 20,
  color = '#18181B',
  filled = false,
  strokeWidth,
}: IconProps) {
  const Cmp = MAP[name] ?? Circle
  return (
    <Cmp
      size={size}
      color={color}
      strokeWidth={strokeWidth ?? 2}
      fill={filled ? color : 'transparent'}
    />
  )
}
