// 상황별 회화 — 오프라인 번들 (PLANNING §6, §12). 한국어 "보여주기" + 사용자 언어 대역
// 사용자 언어 필드는 사용자가 문장의 뜻을 이해하는 용도이고, 상대(한국인)에게 실제로
// 보여주는 것은 ko 필드다. 네트워크 없이 동작해야 하므로 번들 상수.
//
// 번역 원칙: 격식체보다 실제 상황에서 쓰는 구어. 성별에 따라 동사가 활용되는 언어
// (hi/es/ru 등)는 성 중립 구문을 택한다 — 앱은 사용자 성별을 모른다.

// 회화 대역이 준비된 언어 — 통역 지원 언어(langs.ts) 중 ko(원문)를 제외한 전부
export type Lang =
  | 'en'
  | 'ja'
  | 'zh-CN'
  | 'zh-TW'
  | 'vi'
  | 'th'
  | 'id'
  | 'ms'
  | 'fil'
  | 'hi'
  | 'bn'
  | 'fr'
  | 'de'
  | 'es'
  | 'mn'
  | 'ru'
  | 'ar'
  | 'pt'
  | 'it'
  | 'ne'
  | 'uz'
  | 'yue'
  | 'tr'
  | 'km'
  | 'my'
  | 'kk'
export type Phrase = {
  ko: string
} & Record<Lang, string>
export type Scenario = {
  id: string
  title: string
  icon: string
  color: string
  bg: string
  phrases: Phrase[]
}

export const SCENARIOS: Scenario[] = [
  {
    id: 'restaurant',
    title: 'Restaurant',
    icon: 'restaurant',
    color: '#0EA5E9',
    bg: '#F0F9FF',
    phrases: [
      {
        ko: '메뉴판 주세요.',
        en: 'Menu, please.',
        ja: 'メニューをください。',
        'zh-CN': '请给我菜单。',
        'zh-TW': '請給我菜單。',
        vi: 'Cho tôi xin thực đơn.',
        th: 'ขอเมนูหน่อย',
        id: 'Minta menunya.',
        ms: 'Tolong berikan menu.',
        fil: 'Pahingi po ng menu.',
        hi: 'मेन्यू दीजिए।',
        bn: 'মেনুটা দিন।',
        fr: "Le menu, s'il vous plaît.",
        de: 'Die Speisekarte, bitte.',
        es: 'La carta, por favor.',
        mn: 'Цэс өгөөч.',
        ru: 'Меню, пожалуйста.',
        ar: 'القائمة من فضلك.',
        pt: 'O menu, por favor.',
        it: 'Il menu, per favore.',
        ne: 'मेनु दिनुहोस्।',
        uz: 'Menyuni bering.',
        yue: '唔該，俾張餐牌我。',
        tr: 'Menü, lütfen.',
        km: 'សូមម៉ឺនុយ។',
        my: 'မီနူးပေးပါ။',
        kk: 'Мәзірді беріңізші.',
      },
      {
        // 남부 thịt heo / 북부 thịt lợn — 무슬림·종교 제약과 직결되는 문장이라 양쪽 병기
        ko: '이 음식에 돼지고기가 들어가나요?',
        en: 'Does this dish contain pork?',
        ja: 'この料理に豚肉は入っていますか？',
        'zh-CN': '这道菜含有猪肉吗？',
        'zh-TW': '這道菜含有豬肉嗎？',
        vi: 'Món này có thịt heo (thịt lợn) không?',
        th: 'อาหารจานนี้มีหมูไหม',
        // babi(돼지)보다 daging babi(돼지고기)가 식재료 문맥에서 명확 — 할랄 확인 문장
        id: 'Apakah makanan ini mengandung daging babi?',
        ms: 'Adakah hidangan ini mengandungi daging babi?',
        fil: 'May baboy po ba ang pagkaing ito?',
        hi: 'क्या इस व्यंजन में सूअर का मांस है?',
        bn: 'এই খাবারে কি শুয়োরের মাংস আছে?',
        fr: 'Est-ce que ce plat contient du porc ?',
        de: 'Ist in diesem Gericht Schweinefleisch?',
        es: '¿Este plato lleva cerdo?',
        mn: 'Энэ хоолонд гахайн мах орсон уу?',
        ru: 'В этом блюде есть свинина?',
        ar: 'هل يحتوي هذا الطبق على لحم الخنزير؟',
        pt: 'Este prato contém carne de porco?',
        it: 'Questo piatto contiene carne di maiale?',
        ne: 'यो खानामा सुँगुरको मासु छ?',
        uz: "Bu taomda cho'chqa go'shti bormi?",
        yue: '呢個菜有冇豬肉？',
        tr: 'Bu yemekte domuz eti var mı?',
        km: 'ម្ហូបនេះមានសាច់ជ្រូកទេ?',
        my: 'ဒီဟင်းမှာ ဝက်သားပါလား။',
        kk: 'Бұл тағамда шошқа еті бар ма?',
      },
      {
        ko: '덜 맵게 해주세요.',
        en: 'Please make it less spicy.',
        ja: '辛さを控えめにしてください。',
        'zh-CN': '请做得不要太辣。',
        'zh-TW': '請做得不要太辣。',
        vi: 'Cho ít cay thôi ạ.',
        th: 'ขอเผ็ดน้อยหน่อย',
        id: 'Tolong jangan terlalu pedas.',
        ms: 'Tolong jangan terlalu pedas.',
        fil: 'Pakiluto po ng hindi masyadong maanghang.',
        hi: 'कृपया कम तीखा बनाइए।',
        bn: 'একটু কম ঝাল করে দিন।',
        fr: "Moins épicé, s'il vous plaît.",
        de: 'Bitte weniger scharf.',
        es: 'Menos picante, por favor.',
        mn: 'Бага халуун ногоотой хийж өгөөч.',
        ru: 'Пожалуйста, не очень остро.',
        ar: 'لا تجعله حارًا جدًا، من فضلك.',
        pt: 'Menos picante, por favor.',
        it: 'Meno piccante, per favore.',
        ne: 'कम पिरो बनाइदिनुहोस्।',
        uz: 'Kamroq achchiq qiling.',
        yue: '唔該唔好太辣。',
        tr: 'Lütfen az acılı olsun.',
        km: 'សូមកុំហឹរពេក។',
        my: 'အစပ်နည်းနည်းလျှော့ပေးပါ။',
        kk: 'Тым ащы болмасын.',
      },
      {
        ko: '계산서 주세요.',
        en: 'The bill, please.',
        ja: 'お会計をお願いします。',
        'zh-CN': '请结账。',
        'zh-TW': '請結帳。',
        vi: 'Cho tôi tính tiền.',
        th: 'เก็บเงินด้วย',
        id: 'Minta bonnya.',
        ms: 'Tolong bawakan bil.',
        fil: 'Pahingi po ng bill.',
        hi: 'बिल दीजिए।',
        bn: 'বিলটা দিন।',
        fr: "L'addition, s'il vous plaît.",
        de: 'Die Rechnung, bitte.',
        es: 'La cuenta, por favor.',
        mn: 'Тооцоо гаргаж өгөөч.',
        ru: 'Счёт, пожалуйста.',
        ar: 'الحساب من فضلك.',
        pt: 'A conta, por favor.',
        it: 'Il conto, per favore.',
        ne: 'बिल दिनुहोस्।',
        uz: 'Hisobni bering.',
        yue: '唔該埋單。',
        tr: 'Hesap, lütfen.',
        km: 'សូមគិតលុយ។',
        my: 'ငွေရှင်းပါမယ်။',
        kk: 'Есепшотты беріңізші.',
      },
      {
        ko: '카드로 결제할게요.',
        en: "I'll pay by card.",
        ja: 'カードで払います。',
        'zh-CN': '我用信用卡付款。',
        'zh-TW': '我用信用卡付款。',
        vi: 'Tôi trả bằng thẻ.',
        th: 'จ่ายด้วยบัตร',
        id: 'Saya bayar pakai kartu.',
        ms: 'Saya bayar dengan kad.',
        fil: 'Magbabayad po ako gamit ang card.',
        // करना है 구문은 성 중립 (करूँगा/करूँगी 활용 회피)
        hi: 'मुझे कार्ड से भुगतान करना है।',
        bn: 'আমি কার্ডে পেমেন্ট করব।',
        fr: 'Je vais payer par carte.',
        de: 'Ich zahle mit Karte.',
        es: 'Voy a pagar con tarjeta.',
        mn: 'Картаар төлнө.',
        ru: 'Я оплачу картой.',
        ar: 'سأدفع بالبطاقة.',
        pt: 'Vou pagar com cartão.',
        it: 'Pago con la carta.',
        ne: 'म कार्डबाट तिर्छु।',
        uz: "Karta bilan to'layman.",
        yue: '我用卡俾錢。',
        tr: 'Kartla ödeyeceğim.',
        km: 'ខ្ញុំបង់ដោយកាត។',
        my: 'ကတ်နဲ့ ပေးချေမယ်။',
        kk: 'Картамен төлеймін.',
      },
    ],
  },
  {
    id: 'taxi',
    title: 'Taxi',
    icon: 'local_taxi',
    color: '#F97316',
    bg: '#FFF7ED',
    phrases: [
      {
        ko: '이 주소로 가주세요.',
        en: 'Please go to this address.',
        ja: 'この住所までお願いします。',
        'zh-CN': '请到这个地址。',
        'zh-TW': '請到這個地址。',
        vi: 'Làm ơn chở tôi đến địa chỉ này.',
        th: 'ไปตามที่อยู่นี้หน่อย',
        id: 'Tolong ke alamat ini.',
        ms: 'Tolong ke alamat ini.',
        fil: 'Pakihatid po ako sa address na ito.',
        hi: 'कृपया इस पते पर ले चलिए।',
        bn: 'এই ঠিকানায় নিয়ে চলুন।',
        fr: "À cette adresse, s'il vous plaît.",
        de: 'Zu dieser Adresse, bitte.',
        es: 'A esta dirección, por favor.',
        mn: 'Энэ хаяг руу хүргэж өгөөч.',
        ru: 'Отвезите меня по этому адресу, пожалуйста.',
        ar: 'إلى هذا العنوان من فضلك.',
        pt: 'Para este endereço, por favor.',
        it: 'A questo indirizzo, per favore.',
        ne: 'यो ठेगानामा लैजानुहोस्।',
        uz: 'Shu manzilga olib boring.',
        yue: '唔該去呢個地址。',
        tr: 'Lütfen bu adrese gidin.',
        km: 'សូមទៅអាសយដ្ឋាននេះ។',
        my: 'ဒီလိပ်စာကို ပို့ပေးပါ။',
        kk: 'Осы мекенжайға апарыңызшы.',
      },
      {
        ko: '얼마나 걸리나요?',
        en: 'How long will it take?',
        ja: 'どのくらいかかりますか？',
        'zh-CN': '需要多长时间？',
        'zh-TW': '需要多久？',
        vi: 'Mất bao lâu?',
        th: 'ใช้เวลานานแค่ไหน',
        id: 'Berapa lama?',
        ms: 'Berapa lama?',
        fil: 'Gaano po katagal?',
        hi: 'कितना समय लगेगा?',
        bn: 'কত সময় লাগবে?',
        fr: 'Ça prend combien de temps ?',
        de: 'Wie lange dauert es?',
        es: '¿Cuánto tarda?',
        mn: 'Хэр удах вэ?',
        ru: 'Сколько это займёт времени?',
        ar: 'كم يستغرق ذلك؟',
        pt: 'Quanto tempo demora?',
        it: 'Quanto tempo ci vuole?',
        ne: 'कति समय लाग्छ?',
        uz: 'Qancha vaqt ketadi?',
        yue: '要幾耐？',
        tr: 'Ne kadar sürer?',
        km: 'ចំណាយពេលប៉ុន្មាន?',
        my: 'ဘယ်လောက်ကြာမလဲ။',
        kk: 'Қанша уақыт кетеді?',
      },
      {
        ko: '여기서 세워주세요.',
        en: 'Please stop here.',
        ja: 'ここで止めてください。',
        'zh-CN': '请在这里停车。',
        'zh-TW': '請在這裡停車。',
        vi: 'Cho tôi xuống ở đây.',
        th: 'จอดตรงนี้',
        id: 'Tolong berhenti di sini.',
        ms: 'Tolong berhenti di sini.',
        fil: 'Pakihinto po dito.',
        hi: 'यहीं रोक दीजिए।',
        bn: 'এখানে থামুন।',
        fr: "Arrêtez-vous ici, s'il vous plaît.",
        de: 'Halten Sie bitte hier.',
        es: 'Pare aquí, por favor.',
        mn: 'Энд зогсоож өгөөч.',
        ru: 'Остановите здесь, пожалуйста.',
        ar: 'الرجاء التوقف هنا.',
        pt: 'Pare aqui, por favor.',
        it: 'Si fermi qui, per favore.',
        ne: 'यहीँ रोक्नुहोस्।',
        uz: "Shu yerda to'xtating.",
        yue: '唔該喺呢度停。',
        tr: 'Lütfen burada durun.',
        km: 'សូមឈប់ត្រង់នេះ។',
        my: 'ဒီမှာ ရပ်ပေးပါ။',
        kk: 'Осы жерде тоқтатыңызшы.',
      },
      {
        ko: '영수증 주세요.',
        en: 'Receipt, please.',
        ja: '領収書をください。',
        'zh-CN': '请给我收据。',
        'zh-TW': '請給我收據。',
        vi: 'Cho tôi hóa đơn.',
        th: 'ขอใบเสร็จ',
        id: 'Minta struknya.',
        ms: 'Tolong berikan resit.',
        fil: 'Pahingi po ng resibo.',
        hi: 'रसीद दीजिए।',
        bn: 'রসিদ দিন।',
        fr: "Un reçu, s'il vous plaît.",
        de: 'Eine Quittung, bitte.',
        es: 'Un recibo, por favor.',
        mn: 'Баримт өгөөч.',
        ru: 'Дайте чек, пожалуйста.',
        ar: 'الإيصال من فضلك.',
        pt: 'Um recibo, por favor.',
        it: 'Una ricevuta, per favore.',
        ne: 'रसिद दिनुहोस्।',
        uz: 'Chek bering.',
        yue: '唔該俾張收據我。',
        tr: 'Fiş, lütfen.',
        km: 'សូមបង្កាន់ដៃ។',
        my: 'ပြေစာပေးပါ။',
        kk: 'Түбіртек беріңізші.',
      },
    ],
  },
  {
    id: 'hospital',
    title: 'Hospital',
    icon: 'medical_services',
    color: '#EC4899',
    bg: '#FCE7F3',
    phrases: [
      {
        ko: '몸이 아파요.',
        en: "I'm not feeling well.",
        ja: '体調が悪いです。',
        'zh-CN': '我身体不舒服。',
        'zh-TW': '我身體不舒服。',
        vi: 'Tôi thấy không khỏe.',
        th: 'รู้สึกไม่สบาย',
        id: 'Saya merasa tidak enak badan.',
        ms: 'Saya rasa tidak sihat.',
        fil: 'Masama po ang pakiramdam ko.',
        hi: 'मेरी तबीयत ठीक नहीं है।',
        bn: 'আমার শরীর খারাপ লাগছে।',
        fr: 'Je ne me sens pas bien.',
        de: 'Mir geht es nicht gut.',
        es: 'No me siento bien.',
        mn: 'Би өвдөж байна.',
        ru: 'Мне нехорошо.',
        ar: 'لا أشعر أنني بخير.',
        pt: 'Não me sinto bem.',
        it: 'Non mi sento bene.',
        ne: 'मलाई सञ्चो छैन।',
        uz: "O'zimni yomon his qilyapman.",
        yue: '我唔舒服。',
        tr: 'Kendimi iyi hissetmiyorum.',
        km: 'ខ្ញុំមិនស្រួលខ្លួនទេ។',
        my: 'နေမကောင်းဘူး။',
        kk: 'Өзімді нашар сезініп тұрмын.',
      },
      {
        ko: '여기가 아파요.',
        en: 'It hurts here.',
        ja: 'ここが痛いです。',
        'zh-CN': '这里疼。',
        'zh-TW': '這裡痛。',
        vi: 'Tôi bị đau ở đây.',
        th: 'เจ็บตรงนี้',
        id: 'Sakitnya di sini.',
        ms: 'Sakit di sini.',
        fil: 'Masakit po dito.',
        hi: 'यहाँ दर्द हो रहा है।',
        bn: 'এখানে ব্যথা করছে।',
        fr: "J'ai mal ici.",
        de: 'Hier tut es weh.',
        es: 'Me duele aquí.',
        mn: 'Энд өвдөж байна.',
        ru: 'Здесь болит.',
        ar: 'أشعر بألم هنا.',
        pt: 'Dói aqui.',
        it: 'Mi fa male qui.',
        ne: 'यहाँ दुख्छ।',
        uz: "Bu yerim og'riyapti.",
        yue: '呢度痛。',
        tr: 'Burası ağrıyor.',
        km: 'ឈឺត្រង់នេះ។',
        my: 'ဒီနေရာ နာနေတယ်။',
        kk: 'Мына жерім ауырады.',
      },
      {
        // 남부 đậu phộng / 북부 lạc — 알레르기 문장이라 오해 없도록 병기
        ko: '저는 땅콩 알레르기가 있어요.',
        en: 'I am allergic to peanuts.',
        ja: '私はピーナッツアレルギーがあります。',
        'zh-CN': '我对花生过敏。',
        'zh-TW': '我對花生過敏。',
        vi: 'Tôi bị dị ứng với đậu phộng (lạc).',
        // 1인칭 ฉัน은 여성 화자로 읽히므로 생략(앱은 사용자 성별을 모름)
        th: 'แพ้ถั่วลิสง',
        id: 'Saya alergi kacang tanah.',
        ms: 'Saya alah kepada kacang tanah.',
        fil: 'Allergic po ako sa mani.',
        hi: 'मुझे मूँगफली से एलर्जी है।',
        bn: 'আমার চিনাবাদামে অ্যালার্জি আছে।',
        fr: 'Je suis allergique aux cacahuètes.',
        de: 'Ich bin allergisch gegen Erdnüsse.',
        // "Soy alérgico/a" 성별 활용을 피해 tener 구문으로
        es: 'Tengo alergia al cacahuete (maní).',
        mn: 'Надад газрын самрын харшил бий.',
        ru: 'У меня аллергия на арахис.',
        ar: 'لدي حساسية من الفول السوداني.',
        pt: 'Tenho alergia a amendoim.',
        it: "Ho un'allergia alle arachidi.",
        // बदाम은 아몬드·견과류 일반으로 읽힌다 — 땅콩은 मूँगफली
        ne: 'मलाई मूँगफलीको एलर्जी छ।',
        uz: "Menda yeryong'oqqa allergiya bor.",
        yue: '我對花生敏感。',
        tr: 'Yer fıstığına alerjim var.',
        km: 'ខ្ញុំមានអាឡែស៊ីនឹងសណ្តែកដី។',
        my: 'မြေပဲနဲ့ ဓာတ်မတည့်ဘူး။',
        kk: 'Менде жержаңғаққа аллергия бар.',
      },
      {
        ko: '약을 사고 싶어요.',
        en: 'I want to buy medicine.',
        ja: '薬を買いたいです。',
        'zh-CN': '我想买药。',
        'zh-TW': '我想買藥。',
        vi: 'Tôi muốn mua thuốc.',
        th: 'อยากซื้อยา',
        id: 'Saya ingin membeli obat.',
        ms: 'Saya mahu membeli ubat.',
        fil: 'Gusto ko pong bumili ng gamot.',
        hi: 'मुझे दवा खरीदनी है।',
        bn: 'আমি ওষুধ কিনতে চাই।',
        fr: 'Je voudrais acheter des médicaments.',
        de: 'Ich möchte Medikamente kaufen.',
        es: 'Quiero comprar medicamentos.',
        mn: 'Эм худалдаж авмаар байна.',
        ru: 'Я хочу купить лекарство.',
        ar: 'أريد شراء دواء.',
        pt: 'Quero comprar um medicamento.',
        it: 'Vorrei comprare delle medicine.',
        ne: 'मलाई औषधि किन्नु छ।',
        uz: 'Dori sotib olmoqchiman.',
        yue: '我想買藥。',
        tr: 'İlaç almak istiyorum.',
        km: 'ខ្ញុំចង់ទិញថ្នាំ។',
        my: 'ဆေးဝယ်ချင်တယ်။',
        kk: 'Дәрі сатып алғым келеді.',
      },
    ],
  },
  {
    id: 'shopping',
    title: 'Shopping',
    icon: 'shopping_bag',
    color: '#0D9488',
    bg: '#F0FDFA',
    phrases: [
      {
        ko: '이거 얼마예요?',
        en: 'How much is this?',
        ja: 'これはいくらですか？',
        'zh-CN': '这个多少钱？',
        'zh-TW': '這個多少錢？',
        vi: 'Cái này bao nhiêu tiền?',
        th: 'อันนี้ราคาเท่าไหร่',
        id: 'Ini berapa harganya?',
        ms: 'Berapa harga ini?',
        fil: 'Magkano po ito?',
        hi: 'यह कितने का है?',
        bn: 'এটার দাম কত?',
        fr: 'Ça coûte combien ?',
        de: 'Was kostet das?',
        es: '¿Cuánto cuesta esto?',
        mn: 'Энэ ямар үнэтэй вэ?',
        ru: 'Сколько это стоит?',
        ar: 'كم سعر هذا؟',
        pt: 'Quanto custa isto?',
        it: 'Quanto costa questo?',
        ne: 'यो कति पर्छ?',
        uz: 'Bu qancha turadi?',
        yue: '呢個幾多錢？',
        tr: 'Bu ne kadar?',
        km: 'នេះថ្លៃប៉ុន្មាន?',
        my: 'ဒါ ဘယ်လောက်လဲ။',
        kk: 'Бұл қанша тұрады?',
      },
      {
        ko: '입어봐도 될까요?',
        en: 'Can I try this on?',
        ja: '試着してもいいですか？',
        'zh-CN': '我可以试穿吗？',
        'zh-TW': '我可以試穿嗎？',
        vi: 'Tôi mặc thử được không?',
        th: 'ลองใส่ได้ไหม',
        id: 'Boleh saya coba pakai?',
        ms: 'Boleh saya cuba pakai?',
        fil: 'Pwede ko po bang isukat?',
        // 존칭 복수형(सकते हैं)으로 성 중립 유지
        hi: 'क्या इसे पहनकर देखना ठीक रहेगा?',
        bn: 'এটা পরে দেখতে পারি?',
        fr: "Je peux l'essayer ?",
        de: 'Kann ich das anprobieren?',
        es: '¿Puedo probármelo?',
        mn: 'Өмсөж үзэж болох уу?',
        ru: 'Можно примерить?',
        ar: 'هل يمكنني تجربة هذا؟',
        pt: 'Posso experimentar?',
        it: 'Posso provare?',
        ne: 'लगाएर हेर्न मिल्छ?',
        uz: "Kiyib ko'rsam bo'ladimi?",
        yue: '可唔可以試身？',
        tr: 'Deneyebilir miyim?',
        km: 'អាចសាកពាក់បានទេ?',
        my: 'ဝတ်ကြည့်လို့ရမလား။',
        kk: 'Киіп көрсем бола ма?',
      },
      {
        ko: '택스 리펀드 되나요?',
        en: 'Do you offer tax refund?',
        ja: '免税はできますか？',
        'zh-CN': '可以退税吗？',
        'zh-TW': '可以退稅嗎？',
        vi: 'Ở đây có hoàn thuế không?',
        th: 'ขอคืนภาษีได้ไหม',
        id: 'Bisa dapat pengembalian pajak?',
        ms: 'Boleh dapat bayaran balik cukai?',
        fil: 'May tax refund po ba?',
        hi: 'क्या टैक्स रिफंड मिलता है?',
        bn: 'ট্যাক্স রিফান্ড পাওয়া যায়?',
        fr: 'Vous faites la détaxe ?',
        de: 'Bekomme ich die Mehrwertsteuer zurück?',
        es: '¿Hacen devolución de impuestos?',
        mn: 'Татвар буцаалт хийдэг үү?',
        ru: 'Здесь можно вернуть налог?',
        ar: 'هل يوجد استرداد ضريبي؟',
        pt: 'Fazem reembolso de impostos?',
        it: 'Fate il tax free?',
        ne: 'कर फिर्ता पाइन्छ?',
        uz: 'Soliqni qaytarish bormi?',
        yue: '可唔可以退稅？',
        tr: 'Vergi iadesi var mı?',
        km: 'អាចសុំបង្វិលពន្ធវិញបានទេ?',
        my: 'အခွန်ပြန်အမ်းလို့ရလား။',
        kk: 'Салықты қайтаруға бола ма?',
      },
      {
        ko: '깎아주세요.',
        en: 'Can you give me a discount?',
        ja: '安くしてください。',
        'zh-CN': '可以便宜一点吗？',
        'zh-TW': '可以便宜一點嗎？',
        vi: 'Giảm giá cho tôi được không?',
        th: 'ลดราคาหน่อยได้ไหม',
        id: 'Boleh kurang harganya?',
        ms: 'Boleh kurangkan harga?',
        fil: 'Pwede po bang babaan ang presyo?',
        hi: 'थोड़ा कम कीजिए।',
        bn: 'একটু কম করুন।',
        fr: 'Vous pouvez me faire un prix ?',
        de: 'Können Sie mir einen Rabatt geben?',
        es: '¿Me puede hacer un descuento?',
        mn: 'Хямдруулж өгөөч.',
        ru: 'Можно скидку?',
        ar: 'هل يمكن تخفيض السعر؟',
        pt: 'Pode fazer um desconto?',
        it: 'Può farmi uno sconto?',
        ne: 'अलि सस्तो गरिदिनुहोस्।',
        uz: "Arzonroq qilsangiz bo'ladimi?",
        yue: '可唔可以平啲？',
        tr: 'İndirim yapabilir misiniz?',
        km: 'សូមបញ្ចុះតម្លៃបន្តិច។',
        my: 'နည်းနည်းလျှော့ပေးပါ။',
        kk: 'Арзандатыңызшы.',
      },
    ],
  },
  {
    id: 'emergency',
    title: 'Emergency',
    icon: 'emergency',
    color: '#DC2626',
    bg: '#FEE2E2',
    phrases: [
      {
        ko: '도와주세요!',
        en: 'Please help me!',
        ja: '助けてください！',
        'zh-CN': '请帮帮我！',
        'zh-TW': '請幫幫我！',
        // 긴급 시나리오 — 정중한 'Làm ơn giúp tôi'보다 실제로 외치는 표현
        vi: 'Cứu tôi với!',
        th: 'ช่วยด้วย',
        id: 'Tolong saya!',
        ms: 'Tolong saya!',
        // 긴급 외침에는 경어 po를 빼야 긴박감이 산다(다른 문구의 po는 유지)
        fil: 'Tulong!',
        hi: 'मदद कीजिए!',
        bn: 'সাহায্য করুন!',
        fr: 'Au secours !',
        de: 'Hilfe!',
        es: '¡Socorro!',
        mn: 'Туслаарай!',
        ru: 'Помогите!',
        ar: 'النجدة!',
        pt: 'Socorro!',
        it: 'Aiuto!',
        // सहयोग는 협조 요청에 가깝다 — 긴급 구조 외침은 मद्दत
        ne: 'मद्दत गर्नुहोस्!',
        uz: 'Yordam bering!',
        yue: '救命呀！',
        tr: 'İmdat!',
        km: 'ជួយផង!',
        my: 'ကူညီပါ။',
        kk: 'Көмектесіңізші!',
      },
      {
        ko: '경찰을 불러주세요.',
        en: 'Please call the police.',
        ja: '警察を呼んでください。',
        'zh-CN': '请叫警察。',
        'zh-TW': '請叫警察。',
        vi: 'Làm ơn gọi cảnh sát.',
        th: 'ช่วยเรียกตำรวจให้หน่อย',
        id: 'Tolong panggil polisi.',
        ms: 'Tolong panggil polis.',
        fil: 'Pakitawag po ng pulis.',
        hi: 'पुलिस को बुलाइए।',
        bn: 'পুলিশ ডাকুন।',
        fr: "Appelez la police, s'il vous plaît.",
        de: 'Rufen Sie bitte die Polizei.',
        es: 'Llame a la policía, por favor.',
        mn: 'Цагдаа дуудаж өгөөч.',
        ru: 'Вызовите полицию, пожалуйста.',
        ar: 'الرجاء الاتصال بالشرطة.',
        pt: 'Chame a polícia, por favor.',
        it: 'Chiami la polizia, per favore.',
        ne: 'प्रहरी बोलाउनुहोस्।',
        uz: 'Politsiyani chaqiring.',
        yue: '唔該叫警察。',
        tr: 'Lütfen polisi arayın.',
        km: 'សូមហៅប៉ូលិស។',
        my: 'ရဲခေါ်ပေးပါ။',
        kk: 'Полицияны шақырыңызшы.',
      },
      {
        ko: '구급차를 불러주세요.',
        en: 'Please call an ambulance.',
        ja: '救急車を呼んでください。',
        'zh-CN': '请叫救护车。',
        'zh-TW': '請叫救護車。',
        vi: 'Làm ơn gọi xe cấp cứu.',
        th: 'ช่วยเรียกรถพยาบาล',
        id: 'Tolong panggil ambulans.',
        ms: 'Tolong panggil ambulans.',
        fil: 'Pakitawag po ng ambulansya.',
        hi: 'एम्बुलेंस बुलाइए।',
        bn: 'অ্যাম্বুলেন্স ডাকুন।',
        fr: "Appelez une ambulance, s'il vous plaît.",
        de: 'Rufen Sie bitte einen Krankenwagen.',
        es: 'Llame a una ambulancia, por favor.',
        mn: 'Түргэн тусламж дуудаж өгөөч.',
        ru: 'Вызовите скорую, пожалуйста.',
        ar: 'الرجاء الاتصال بالإسعاف.',
        pt: 'Chame uma ambulância, por favor.',
        it: "Chiami un'ambulanza, per favore.",
        ne: 'एम्बुलेन्स बोलाउनुहोस्।',
        uz: 'Tez yordam chaqiring.',
        yue: '唔該叫救護車。',
        tr: 'Lütfen ambulans çağırın.',
        km: 'សូមហៅរថយន្តសង្គ្រោះ។',
        my: 'လူနာတင်ကား ခေါ်ပေးပါ။',
        kk: 'Жедел жәрдем шақырыңызшы.',
      },
      {
        ko: '지갑을 잃어버렸어요.',
        en: 'I lost my wallet.',
        ja: '財布をなくしました。',
        'zh-CN': '我的钱包丢了。',
        'zh-TW': '我的錢包不見了。',
        vi: 'Tôi bị mất ví.',
        th: 'ทำกระเป๋าสตางค์หาย',
        id: 'Dompet saya hilang.',
        ms: 'Dompet saya hilang.',
        fil: 'Nawala po ang wallet ko.',
        hi: 'मेरा बटुआ खो गया है।',
        bn: 'আমার মানিব্যাগ হারিয়ে গেছে।',
        fr: "J'ai perdu mon portefeuille.",
        de: 'Ich habe meine Geldbörse verloren.',
        es: 'He perdido mi billetera (cartera).',
        mn: 'Би түрийвчээ гээчихлээ.',
        // потерял/потеряла 성별 활용을 피해 무주어 구문으로
        ru: 'У меня пропал кошелёк.',
        ar: 'لقد فقدت محفظتي.',
        pt: 'Perdi minha carteira.',
        it: 'Ho perso il portafoglio.',
        ne: 'मेरो पर्स हरायो।',
        uz: "Hamyonimni yo'qotib qo'ydim.",
        yue: '我唔見咗個銀包。',
        tr: 'Cüzdanımı kaybettim.',
        km: 'ខ្ញុំបាត់កាបូបលុយ។',
        my: 'ပိုက်ဆံအိတ် ပျောက်သွားတယ်။',
        kk: 'Әмиянымды жоғалтып алдым.',
      },
    ],
  },
  {
    id: 'hotel',
    title: 'Hotel',
    icon: 'hotel',
    color: '#F59E0B',
    bg: '#FEF3C7',
    phrases: [
      {
        ko: '체크인하고 싶어요.',
        en: "I'd like to check in.",
        ja: 'チェックインをお願いします。',
        'zh-CN': '我想办理入住。',
        'zh-TW': '我想辦理入住。',
        vi: 'Tôi muốn nhận phòng.',
        th: 'ขอเช็คอินหน่อย',
        id: 'Saya mau check-in.',
        ms: 'Saya mahu daftar masuk.',
        fil: 'Gusto ko pong mag-check in.',
        hi: 'मुझे चेक-इन करना है।',
        bn: 'আমি চেক-ইন করতে চাই।',
        fr: "Je voudrais m'enregistrer.",
        de: 'Ich möchte einchecken.',
        es: 'Quiero hacer el check-in.',
        mn: 'Check-in хиймээр байна.',
        ru: 'Я хочу заселиться.',
        ar: 'أريد تسجيل الوصول.',
        pt: 'Quero fazer o check-in.',
        it: 'Vorrei fare il check-in.',
        ne: 'मलाई चेक-इन गर्नु छ।',
        uz: 'Check-in qilmoqchiman.',
        yue: '我想check-in。',
        tr: 'Check-in yapmak istiyorum.',
        km: 'ខ្ញុំចង់ចុះឈ្មោះចូលស្នាក់នៅ។',
        my: 'Check-in လုပ်ချင်တယ်။',
        kk: 'Тіркелгім келеді.',
      },
      {
        ko: '와이파이 비밀번호가 뭐예요?',
        en: 'What is the Wi-Fi password?',
        ja: 'Wi-Fiのパスワードは何ですか？',
        'zh-CN': 'Wi-Fi密码是多少？',
        'zh-TW': 'Wi-Fi密碼是多少？',
        vi: 'Mật khẩu Wi-Fi là gì?',
        th: 'รหัส Wi-Fi คืออะไร',
        id: 'Apa kata sandi Wi-Fi-nya?',
        ms: 'Apa kata laluan Wi-Fi?',
        fil: 'Ano po ang password ng Wi-Fi?',
        hi: 'वाई-फ़ाई का पासवर्ड क्या है?',
        bn: 'ওয়াই-ফাই পাসওয়ার্ড কী?',
        fr: 'Quel est le mot de passe du Wi-Fi ?',
        de: 'Wie lautet das WLAN-Passwort?',
        es: '¿Cuál es la contraseña del wifi?',
        mn: 'Wi-Fi-ийн нууц үг юу вэ?',
        ru: 'Какой пароль от Wi-Fi?',
        ar: 'ما هي كلمة سر الواي فاي؟',
        pt: 'Qual é a senha (palavra-passe) do Wi-Fi?',
        it: 'Qual è la password del Wi-Fi?',
        ne: 'वाइफाइको पासवर्ड के हो?',
        uz: 'Wi-Fi paroli nima?',
        yue: 'Wi-Fi密碼係咩？',
        tr: 'Wi-Fi şifresi nedir?',
        km: 'លេខសម្ងាត់ Wi-Fi ជាអ្វី?',
        my: 'Wi-Fi စကားဝှက် ဘာလဲ။',
        kk: 'Wi-Fi құпия сөзі қандай?',
      },
      {
        ko: '짐을 맡길 수 있을까요?',
        en: 'Can I leave my luggage here?',
        ja: '荷物を預けられますか？',
        'zh-CN': '可以寄存行李吗？',
        'zh-TW': '可以寄放行李嗎？',
        vi: 'Tôi gửi hành lý ở đây được không?',
        th: 'ฝากกระเป๋าได้ไหม',
        // barang(물건 일반)은 호텔 수하물 보관 맥락에 너무 넓다 → bagasi
        id: 'Bisa titip bagasi di sini?',
        // simpan은 화자가 직접 보관하는 뉘앙스 → 맡긴다는 뜻의 tinggalkan
        ms: 'Boleh saya tinggalkan bagasi di sini?',
        fil: 'Pwede po bang iwan dito ang bagahe ko?',
        hi: 'क्या सामान यहाँ रख सकते हैं?',
        bn: 'এখানে ব্যাগ রাখা যাবে?',
        fr: 'Je peux laisser mes bagages ici ?',
        de: 'Kann ich mein Gepäck hier lassen?',
        es: '¿Puedo dejar mi equipaje aquí?',
        mn: 'Ачаагаа энд үлдээж болох уу?',
        ru: 'Можно оставить багаж здесь?',
        ar: 'هل يمكنني ترك أمتعتي هنا؟',
        pt: 'Posso deixar a minha bagagem aqui?',
        it: 'Posso lasciare i bagagli qui?',
        ne: 'सामान यहाँ राख्न मिल्छ?',
        uz: "Yukimni shu yerga qoldirsam bo'ladimi?",
        yue: '可唔可以寄存行李？',
        tr: 'Bagajımı burada bırakabilir miyim?',
        km: 'អាចផ្ញើឥវ៉ាន់នៅទីនេះបានទេ?',
        my: 'အထုပ်အပိုး ဒီမှာ ထားလို့ရမလား။',
        kk: 'Жүгімді осында қалдырсам бола ма?',
      },
      {
        ko: '체크아웃 시간이 언제예요?',
        en: 'What time is check-out?',
        ja: 'チェックアウトは何時ですか？',
        'zh-CN': '退房时间是几点？',
        'zh-TW': '退房時間是幾點？',
        vi: 'Mấy giờ phải trả phòng?',
        th: 'เช็คเอาท์กี่โมง',
        id: 'Jam berapa check-out?',
        ms: 'Pukul berapa daftar keluar?',
        fil: 'Anong oras po ang check-out?',
        hi: 'चेक-आउट का समय क्या है?',
        bn: 'চেক-আউট কখন?',
        fr: 'Le check-out est à quelle heure ?',
        de: 'Wann ist der Check-out?',
        es: '¿A qué hora es la salida?',
        mn: 'Хэдэн цагт гарах вэ?',
        ru: 'Во сколько выселение?',
        ar: 'متى موعد تسجيل المغادرة؟',
        pt: 'A que horas é o check-out?',
        it: 'A che ora è il check-out?',
        ne: 'चेक-आउट कति बजे हो?',
        uz: 'Check-out soat nechada?',
        yue: '幾點退房？',
        tr: 'Check-out saat kaçta?',
        km: 'ចេញបន្ទប់ម៉ោងប៉ុន្មាន?',
        my: 'Check-out ဘယ်အချိန်လဲ။',
        kk: 'Нөмірден қашан шығу керек?',
      },
    ],
  },
]

export function findScenario(id?: string) {
  return SCENARIOS.find((s) => s.id === id) ?? SCENARIOS[0]
}
